### ISSUE TITLE
openshift-tuned scalability issues

### ISSUE THREAD

**Issue by sjug** [openshift/openshift-tuned#29]
In trying to reach cluster limits openshift-tuned had low level failures causing failure looping. These failures caused the Lists to fire many times per second further causing etcd to lock. 

A few fixes need to be implemented:
- Aggressive timed back-off
- Use of informers for any List and Watch calls

**Comment by jmencak** [comment]
https://github.com/openshift/openshift-tuned/pull/30

**Comment by jmencak** [comment]
This has been addressed by:
https://github.com/openshift/openshift-tuned/pull/34
https://github.com/openshift/cluster-node-tuning-operator/pull/96
https://github.com/openshift/openshift-tuned/pull/35
https://github.com/openshift/cluster-node-tuning-operator/pull/98
